USE [aspnet-MDC]
GO

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'Province')  
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AG','Agrigento','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AL','Alessandria','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AN','Ancona','Marche')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AO','Aosta','Valle d''Aosta')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AQ','L''Aquila','Abruzzo')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AR','Arezzo','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AP','Ascoli-Piceno','Marche')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AT','Asti','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('AV','Avellino','Campania')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BA','Bari','Puglia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BT','Barletta-Andria-Trani','Puglia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BL','Belluno','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BN','Benevento','Campania')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BG','Bergamo','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BI','Biella','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BO','Bologna','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BZ','Bolzano','Trentino Alto Adige')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BS','Brescia','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('BR','Brindisi','Puglia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CA','Cagliari','Sardegna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CL','Caltanissetta','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CB','Campobasso','Molise')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CE','Caserta','Campania')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CT','Catania','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CZ','Catanzaro','Calabria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CH','Chieti','Abruzzo')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CO','Como','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CS','Cosenza','Calabria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CR','Cremona','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('KR','Crotone','Calabria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('CN','Cuneo','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('EN','Enna','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('FM','Fermo','Marche')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('FE','Ferrara','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('FI','Firenze','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('FG','Foggia','Puglia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('FC','Forli-Cesena','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('FR','Frosinone','Lazio')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('GE','Genova','Liguria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('GO','Gorizia','Friuli Venezia Giulia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('GR','Grosseto','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('IM','Imperia','Liguria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('IS','Isernia','Molise')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SP','La-Spezia','Liguria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('LT','Latina','Lazio')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('LE','Lecce','Puglia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('LC','Lecco','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('LI','Livorno','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('LO','Lodi','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('LU','Lucca','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MC','Macerata','Marche')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MN','Mantova','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MS','Massa-Carrara','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MT','Matera','Basilicata')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('ME','Messina','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MI','Milano','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MO','Modena','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('MB','Monza-Brianza','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('NA','Napoli','Campania')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('NO','Novara','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('NU','Nuoro','Sardegna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('OR','Oristano','Sardegna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PD','Padova','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PA','Palermo','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PR','Parma','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PV','Pavia','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PG','Perugia','Umbria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PU','Pesaro-Urbino','Marche')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PE','Pescara','Abruzzo')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PC','Piacenza','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PI','Pisa','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PT','Pistoia','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PN','Pordenone','Friuli Venezia Giulia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PZ','Potenza','Basilicata')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('PO','Prato','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RG','Ragusa','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RA','Ravenna','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RC','Reggio-Calabria','Calabria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RE','Reggio-Emilia','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RI','Rieti','Lazio')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RN','Rimini','Emilia Romagna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RM','Roma','Lazio')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('RO','Rovigo','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SA','Salerno','Campania')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SS','Sassari','Sardegna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SV','Savona','Liguria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SI','Siena','Toscana')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SR','Siracusa','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SO','Sondrio','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('SU','Sud Sardegna','Sardegna')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TA','Taranto','Puglia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TE','Teramo','Abruzzo')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TR','Terni','Umbria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TO','Torino','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TP','Trapani','Sicilia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TN','Trento','Trentino Alto Adige')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TV','Treviso','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('TS','Trieste','Friuli Venezia Giulia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('UD','Udine','Friuli Venezia Giulia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VA','Varese','Lombardia')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VE','Venezia','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VB','Verbania','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VC','Vercelli','Piemonte')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VR','Verona','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VV','Vibo-Valentia','Calabria')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VI','Vicenza','Veneto')
	INSERT INTO [dbo].[Province] ([Sigla], [Descrizione], [Regione]) VALUES ('VT','Viterbo','Lazio')

GO