//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socio
    {
        public int IdSocio { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CodifeFiscale { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string ComuneNascita { get; set; }
        public string Sesso { get; set; }
        public System.DateTime DataIscrizione { get; set; }
        public string Email { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string IndirizzoResidenza { get; set; }
        public string ComuneResidenza { get; set; }
        public string ProvinciaResidenza { get; set; }
        public string Cap { get; set; }
    }
}
